name: receiver
image:
  version: v0.0.2

namespace:
  name: receiver
  create: true

receiverToAllowTransmitterNetworkPolicy:
  transmitterLabel: transmitter
  create: true
  namespace:
    name: transmitter