apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
