apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace.name }}
data:
  URL: "{{ .Values.transmitterNetworkPolicy.namespace.name }}.{{ .Values.transmitterNetworkPolicy.receiverLabel }}.svc.cluster.local"
  SECS: "{{ .Values.repeaterSeconds}}"
  TIMEOUT: "{{ .Values.callTimeout}}"