apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: "mauxas/golang-transmitter:{{ .Values.image.version }}"
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: {{ .Values.name}}
        ports:
        - containerPort: 80