apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-allow-egress-to-receiver-pod
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name}}
  policyTypes:
  - Egress
  egress:
    - to:
      - namespaceSelector: 
          matchLabels: 
            kubernetes.io/metadata.name: "kube-system"
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      - namespaceSelector: 
          matchLabels: 
            kubernetes.io/metadata.name: {{ .Values.transmitterNetworkPolicy.namespace.name }}
        podSelector:
          matchLabels:
            app: {{ .Values.transmitterNetworkPolicy.receiverLabel }}